In [1]:
#20260506
import pandas as pd

In [2]:
df = pd.read_csv("Employees.csv")
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    str
 2   LAST_NAME       111 non-null    str
 3   EMAIL           111 non-null    str
 4   PHONE_NUMBER    111 non-null    str
 5   HIRE_DATE       111 non-null    str
 6   JOB_ID          111 non-null    str
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 9.7 KB

In [4]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [5]:
commission_mean = round(df['COMMISSION_PCT'].mean(),2)
commission_mean

np.float64(0.22)

In [6]:
df['COMMISSION_PCT'].median()

np.float64(0.2)

In [7]:
df["COMMISSION_PCT"].fillna(commission_mean,inplace= True)

C:\Users\niroj\AppData\Local\Temp\ipykernel_20024\1779951445.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["COMMISSION_PCT"].fillna(commission_mean,inplace= True)

0      0.22
1      0.22
2      0.22
3      0.22
4      0.22
       ...
106    0.22
107    0.22
108    0.22
109    0.22
110    0.22
Name: COMMISSION_PCT, Length: 111, dtype: float64

In [8]:
### advised to use mode for the categorical column if they have any null value to be filled.

In [9]:
manager_mode = df['MANAGER_ID'].mode()[0]
manager_mode

np.float64(100.0)

In [10]:
department_mode = df['DEPARTMENT_ID'].mode()[0]
department_mode

np.float64(50.0)

In [11]:
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(manager_mode)
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(department_mode)

In [12]:
df['DEPARTMENT_ID'].isnull().sum()

np.int64(0)

In [13]:
'''
still there is null, because if we have multiple values with same frequency, panda will  not decide on 
which mode it will use, so we have to use the 0th index and specify that
'''

'\nstill there is null, because if we have multiple values with same frequency, panda will  not decide on \nwhich mode it will use, so we have to use the 0th index and specify that\n'

### drop data

In [14]:
df = df.dropna()
# parameters used in dropna
#axis = 0 means row and axis=1 means column
#how -> any/all
# basic idea is for how='all' to work, there need to be ALL the values as null.

In [15]:
# new dataset
#20260507
fraud = pd.read_csv("Fraud Detection Dataset.csv")
fraud

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [16]:
fraud.info()

<class 'pandas.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  str
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  str
 4   Time_of_Transaction               48448 non-null  float64
 5   Device_Used                       48527 non-null  str
 6   Location                          48453 non-null  str
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    48531 non-null  str
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(2), int64(5), str(5)
memory usage: 4.7 MB

In [17]:
fraud.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [18]:
fraud['Time_of_Transaction'].unique()

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [19]:
fraud['Device_Used'].unique()

<StringArray>
['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device']
Length: 5, dtype: str

In [21]:
fraud['Time_of_Transaction'] = fraud['Time_of_Transaction'].fillna(0)

In [23]:
fraud['Device_Used'] = fraud['Device_Used'].fillna('Unknown Device')

In [24]:
fraud['Location'] = fraud['Location'].fillna('Unknown Location')

In [29]:
fraud['Payment_Method'] = fraud['Payment_Method'].fillna('Unknown Method')

In [30]:
fraud.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                            0
Location                               0
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                         0
Fraudulent                             0
Payment_method                         0
dtype: int64

In [31]:
fraud['Time_of_Transaction'] = fraud['Time_of_Transaction'].astype(int)

In [32]:
fraud.info()

<class 'pandas.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  str
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  str
 4   Time_of_Transaction               51000 non-null  int64
 5   Device_Used                       51000 non-null  str
 6   Location                          51000 non-null  str
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    51000 non-null  str
 11  Fraudulent                        51000 non-null  int64
 12  Payment_method                    51000 non-null  str
dtypes: float64(1), int64(6), str(6)
memory usage: 5.1 MB