In [1]:
#20260511

In [2]:
import pandas as pd

In [4]:
df= pd.read_csv("Employees.csv")
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [6]:
df['COMMISSION_PCT'] = df["COMMISSION_PCT"].fillna(0.22)
df["MANAGER_ID"] = df["MANAGER_ID"].fillna(100.0)
df["DEPARTMENT_ID"] = df["DEPARTMENT_ID"].fillna(50.0)

In [7]:
df["MANAGER_ID"] = df["MANAGER_ID"].astype(int)
df["DEPARTMENT_ID"] = df["DEPARTMENT_ID"].astype(int)

In [8]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    str
 2   LAST_NAME       111 non-null    str
 3   EMAIL           111 non-null    str
 4   PHONE_NUMBER    111 non-null    str
 5   HIRE_DATE       111 non-null    datetime64[us]
 6   JOB_ID          111 non-null    str
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  111 non-null    float64
 9   MANAGER_ID      111 non-null    int64
 10  DEPARTMENT_ID   111 non-null    int64
dtypes: datetime64[us](1), float64(1), int64(4), str(5)
memory usage: 9.7 KB

In [ ]:
'''
groupby()
aggregate function -> mean() max() min() count() sum()

If we use groupby clause in our analysis then aggregate function must be used
If we only use aggregate function then group by clause is not compulsory to use
'''

In [11]:
# Find total employees working in each departments
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count().reset_index()
emp_dep

    DEPARTMENT_ID  EMPLOYEE_ID
0              10            1
1              20            2
2              30            6
3              40            2
4              50           46
5              60            5
6              70            2
7              80           34
8              90            3
9             100            6
10            110            4